name: Storage API build

on:
  pull_request:
    paths:
      - ".github/workflows/build.yaml"
      - "src/**"
      - "migrations/**"
      - "__tests__/**"
      - "schemas/**"
      - "package.json"
      - "yarn.lock"
      - "Dockerfile"
      - "ecosystem.config.js"
      - "tsconfig.json"
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yaml"
      - "src/**"
      - "migrations/**"
      - "__tests__/**"
      - "schemas/**"
      - "package.json"
      - "yarn.lock"
      - "Dockerfile"
      - "ecosystem.config.js"
      - "tsconfig.json"

jobs:
  storage-api-build:
    runs-on: ubuntu-latest

    name: Node build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-storage-api-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-storage-api-

      - run: yarn install --frozen-lockfile --non-interactive

      - run: yarn run build
